# Generated by Django 4.1.7 on 2023-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pre_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=21, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
            ],
        ),
    ]
