# Generated by Django 4.1.7 on 2023-03-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recording', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_registration',
            options={'verbose_name': 'Передзапис', 'verbose_name_plural': 'Передзапис'},
        ),
    ]
