# Generated by Django 4.1.7 on 2023-03-28 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recording', '0002_alter_pre_registration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_registration',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
