# Generated by Django 4.1.7 on 2023-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_recording', '0005_alter_pre_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_registration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
